### ISSUE TITLE
Additional files to PyPI released tarball

### ISSUE THREAD

**Issue by sandrotosi** [iamseth/python-zenoss#11]
Hey!
there are several files in git which are missing in the tarball released on PyPI: most importantly LICENSE.txt, but then also tests, examples and maybe README.md and requirements.txt would be helpful.

the absence of the license file, and the fact the license is not explicitly stated anywhere in the pypi tarball, makes it a rather important bug.

thanks for considering

**Comment by iamseth** [comment]
Thanks for pointing that out. I'll take a look when I have some time.
