### ISSUE TITLE
Can't connect with SSL

### ISSUE THREAD

**Issue by mohsin106** [iamseth/python-zenoss#16]
We launched a new Zenoss instance and it now uses SSL. I'm trying to use your code to get devices from my new Zenoss instance but I keep getting this error message:

File "/usr/lib/python2.6/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:492: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

I have access to the certificate file from the new Zenoss instance and tried using it in the script but it does not work. Here is how I configured to use the certificate file:

def __init__(self, host, username, password, ssl_verify='/home/user/filename.cer'):
        self.__host = host
        self.__session = requests.Session()
        self.__session.auth = (username, password)
        self.__session.verify = ssl_verify
        self.__req_count = 0

If I set ssl_verify equal to **False** the script works and pulls all the devices but does give a "InsecureRequestWarning: Unverified HTTPS request is being made." warning. I'm trying to use SSL but can't get it to work. Can you please point me in the right direction?

Thanks
Mohsin

**Comment by iamseth** [comment]
This is no longer an actively maintained project. See README.
