### ISSUE TITLE
Cannot find any API to get the list of devices based on the group name in zenoss?

### ISSUE THREAD

**Issue by amith-reddy** [iamseth/python-zenoss#6]
I am not able to find any API to get the list of devices based on the group name in zenoss? 
Let me know if it can be achieved using some workaround.

**Comment by iamseth** [comment]
I think the pull #12 should do what you want. As soon as it's a little better documented, I'll merge it and push to PyPi.

**Comment by iamseth** [comment]
This is no longer an actively maintained project. See README.
