### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by vasyapupkin123456** [iamseth/python-zenoss#9]
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

How to run request with verify=False ?

**Comment by stevegoossens** [comment]
If you look in the constructor you can see the option:
```python
def __init__(self, host, username, password, ssl_verify=True):
```
so just use the argument `ssl_verify=False` to disable host SSL cert verification


If you need SSL client cert authentication, you can try my fork: https://github.com/stevegoossens/python-zenoss/tree/with-cert
